server:
  port: 3000

# Supabase Configuration
supabase:
  url: https://jfznfxwatpxwqoasszgh.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmem5meHdhdHB4d3FvYXNzemdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Mzg1NzIsImV4cCI6MjA2MTQxNDU3Mn0._8mpyWZ43SQcgFV6LLtxQpdVLfbqEQ2sf0XcYpeU6sw

# Ensure Spring Boot knows about this file if it wasn't automatically picked up
# spring:
#   config:
#     import: optional:application.yml
